version: "2"

linters:
  default: all
  disable:
    - depguard
    - exhaustruct
    - ireturn
    - noinlineerr
    - paralleltest
    - revive
    - wsl
    - wsl_v5
    - cyclop
    - err113
    - funlen
    - gochecknoglobals
    - gocognit
    - godox
    - gosmopolitan
    - lll
    - mnd
    - varnamelen
    - godoclint
    - intrange
    - nlreturn
    - gosec
    - govet
    - prealloc
    - musttag
    - godot

  settings:
    errcheck:
      exclude-functions:
        - fmt.Fprintf
        - fmt.Fprintln
        - fmt.Printf
        - fmt.Println
